/**
 * seed-leagues.ts
 *
 * Ingests data from all leagues defined in src/scripts/leagues.json
 * (generated by parse-leagues.ts from Ligas.xlsx).
 *
 * Features:
 *   ✓ Incremental — skips fixtures already ingested (IngestionCheckpoint per league)
 *   ✓ Parallel   — p-limit(CONCURRENCY) leagues at the same time
 *   ✓ Batch      — createMany + skipDuplicates for MatchEvent (10–20× faster)
 *   ✓ Resilient  — per-league error isolation, seed never aborts mid-run
 *
 * Run:
 *   npm run seed:leagues
 *   npx cross-env NODE_ENV=development ts-node prisma/seed-leagues.ts
 *
 * ⚠  Only runs when NODE_ENV=development.
 */

import "dotenv/config";
import * as fs from "fs";
import * as path from "path";
import pLimit from "p-limit";
import { PrismaClient } from "@prisma/client";
import { ingestLeagueViaFixtures } from "../src/ingestion/fixture-first.ingestion.service";
import type { LeagueSeed } from "../src/scripts/parse-leagues";

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/**
 * How many leagues to process in this run.
 * Set to Infinity to process all leagues in leagues.json.
 */
const MAX_LEAGUES = 20;

/**
 * Finished fixtures per league that trigger event ingestion.
 * Each = 1 API call to /events. Keep low on trial plans.
 */
const MAX_FINISHED_FIXTURES = 10;

/**
 * Fixture pages per league (Sportmonks: 25 fixtures/page).
 * 4 pages × 25 = ~100 fixtures per league.
 */
const FIXTURE_PAGES = 4;

/**
 * Leagues processed in parallel.
 * Each league may make several API calls; keep ≤ 5 to stay under rate limits.
 * Sportmonks typical rate limit: 100 req/min → 3 leagues × ~10 calls = 30 req/batch.
 */
const CONCURRENCY = 3;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const log = (msg: string) =>
  console.log(`[seed-leagues] ${new Date().toISOString().slice(11, 19)}  ${msg}`);

function loadLeagues(): LeagueSeed[] {
  const jsonPath = path.resolve(__dirname, "../src/scripts/leagues.json");
  if (!fs.existsSync(jsonPath)) {
    throw new Error(`leagues.json not found at ${jsonPath}. Run: npm run parse:leagues`);
  }
  return JSON.parse(fs.readFileSync(jsonPath, "utf-8")) as LeagueSeed[];
}

// ---------------------------------------------------------------------------
// Checkpoint helpers
// ---------------------------------------------------------------------------

async function getCheckpoint(leagueExternalId: number): Promise<Date | null> {
  const row = await prisma.ingestionCheckpoint.findUnique({
    where: { leagueExternalId },
    select: { lastFixtureDate: true },
  });
  return row?.lastFixtureDate ?? null;
}

async function saveCheckpoint(leagueExternalId: number, lastFixtureDate: Date | null) {
  await prisma.ingestionCheckpoint.upsert({
    where: { leagueExternalId },
    update: { lastFixtureDate: lastFixtureDate ?? undefined },
    create: { leagueExternalId, lastFixtureDate: lastFixtureDate ?? undefined },
  });
}

// ---------------------------------------------------------------------------
// Per-league worker
// ---------------------------------------------------------------------------

interface LeagueResult {
  league: LeagueSeed;
  success: boolean;
  fixturesTotal: number;
  fixturesNew: number;
  eventsTotal: number;
  error?: string;
}

async function processLeague(league: LeagueSeed, index: number, total: number): Promise<LeagueResult> {
  const tag = `[${index + 1}/${total}] "${league.name}" (id=${league.id}, ${league.country})`;
  log(`▶ ${tag}`);

  try {
    // Read checkpoint — enables incremental mode
    const sinceDate = await getCheckpoint(league.id);
    if (sinceDate) {
      log(`  ↳ Incremental since ${sinceDate.toISOString().slice(0, 10)}`);
    }

    const result = await ingestLeagueViaFixtures(league.id, {
      maxFinishedFixtures: MAX_FINISHED_FIXTURES,
      maxPages: FIXTURE_PAGES,
      sinceDate: sinceDate ?? undefined,
    });

    // Save checkpoint — advance to today so next run is truly incremental
    await saveCheckpoint(league.id, new Date());

    log(`  ✓ fixtures=${result.fixturesTotal} new=${result.fixturesNew} events=${result.eventsTotal}`);

    return {
      league,
      success: true,
      fixturesTotal: result.fixturesTotal,
      fixturesNew: result.fixturesNew,
      eventsTotal: result.eventsTotal,
    };
  } catch (err) {
    const msg = (err as Error).message;
    log(`  ✗ Failed: ${msg}`);
    return { league, success: false, fixturesTotal: 0, fixturesNew: 0, eventsTotal: 0, error: msg };
  }
}

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

async function printSummary() {
  const [leagues, seasons, teams, players, matches, events] = await Promise.all([
    prisma.league.count(),
    prisma.season.count(),
    prisma.team.count(),
    prisma.player.count({ where: { source: "sportmonks" } }),
    prisma.match.count(),
    prisma.matchEvent.count(),
  ]);

  const withCoords = await prisma.matchEvent.count({
    where: { x: { not: null }, y: { not: null } },
  });

  log("");
  log("── DB Summary ───────────────────────────────────────────");
  log(`  Leagues    : ${leagues}`);
  log(`  Seasons    : ${seasons}`);
  log(`  Teams      : ${teams}`);
  log(`  Players    : ${players}`);
  log(`  Matches    : ${matches}`);
  log(`  Events     : ${events}`);
  log(`  w/ coords  : ${withCoords} (${events > 0 ? Math.round((withCoords / events) * 100) : 0}%)`);
  log("─────────────────────────────────────────────────────────");

  if (events > 0 && withCoords === 0) {
    log("⚠  No coordinates found — Sportmonks only includes x/y on Enterprise plans.");
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  if (process.env.NODE_ENV !== "development") {
    console.error("[seed-leagues] ❌  Aborted: NODE_ENV must be 'development'.");
    process.exit(1);
  }

  const allLeagues = loadLeagues();
  const toProcess = MAX_LEAGUES === Infinity
    ? allLeagues
    : allLeagues.slice(0, MAX_LEAGUES);

  log(`Config: MAX_LEAGUES=${MAX_LEAGUES}  MAX_FINISHED_FIXTURES=${MAX_FINISHED_FIXTURES}  FIXTURE_PAGES=${FIXTURE_PAGES}  CONCURRENCY=${CONCURRENCY}`);
  log(`Loaded ${allLeagues.length} leagues — processing ${toProcess.length}`);

  // Parallel processing with concurrency limit
  const limit = pLimit(CONCURRENCY);
  const results = await Promise.all(
    toProcess.map((league, i) => limit(() => processLeague(league, i, toProcess.length))),
  );

  // Aggregate
  const succeeded = results.filter((r) => r.success);
  const failed    = results.filter((r) => !r.success);
  const totalEvents   = results.reduce((s, r) => s + r.eventsTotal, 0);
  const totalFixtures = results.reduce((s, r) => s + r.fixturesNew, 0);

  log(`\n── Run Summary ──────────────────────────────────────────`);
  log(`  Processed  : ${toProcess.length}`);
  log(`  Succeeded  : ${succeeded.length}`);
  log(`  Failed     : ${failed.length}`);
  log(`  New fixtures ingested : ${totalFixtures}`);
  log(`  Events inserted       : ${totalEvents}`);

  if (failed.length > 0) {
    log(`\n  Failed leagues:`);
    failed.forEach((r) => log(`    • ${r.league.name} (id=${r.league.id}) — ${r.error}`));
  }

  await printSummary();
  log("Done.");
}

main()
  .catch((err) => {
    console.error("[seed-leagues] Fatal error:", err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
